using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Finanzauto.Infrastructure.Persistence.Migrations;

public partial class CustomerIntegerIdentity : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        // La transacción de EF conserva clientes, pedidos y fechas mientras cambia ambas claves.
        migrationBuilder.Sql("""
            LOCK TABLE "Customers", "Orders" IN ACCESS EXCLUSIVE MODE;
            ALTER TABLE "Customers" DISABLE TRIGGER "TR_Customers_AuditDates";
            ALTER TABLE "Orders" DISABLE TRIGGER "TR_Orders_AuditDates";

            ALTER TABLE "Customers" ADD COLUMN "NewCustomerId" integer GENERATED BY DEFAULT AS IDENTITY;
            ALTER TABLE "Orders" ADD COLUMN "NewCustomerId" integer;
            UPDATE "Orders" AS o SET "NewCustomerId" = c."NewCustomerId"
            FROM "Customers" AS c WHERE o."CustomerId" = c."CustomerId";
            ALTER TABLE "Orders" ALTER COLUMN "NewCustomerId" SET NOT NULL;

            ALTER TABLE "Orders" DROP CONSTRAINT "FK_Orders_Customers_CustomerId";
            ALTER TABLE "Customers" DROP CONSTRAINT "PK_Customers";
            ALTER TABLE "Orders" DROP COLUMN "CustomerId";
            ALTER TABLE "Customers" DROP COLUMN "CustomerId";
            ALTER TABLE "Customers" RENAME COLUMN "NewCustomerId" TO "CustomerId";
            ALTER TABLE "Orders" RENAME COLUMN "NewCustomerId" TO "CustomerId";
            ALTER SEQUENCE "Customers_NewCustomerId_seq" RENAME TO "Customers_CustomerId_seq";

            ALTER TABLE "Customers" ADD CONSTRAINT "PK_Customers" PRIMARY KEY ("CustomerId");
            CREATE INDEX "IX_Orders_CustomerId" ON "Orders" ("CustomerId");
            ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Customers_CustomerId"
                FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE CASCADE;

            ALTER TABLE "Customers" ENABLE TRIGGER "TR_Customers_AuditDates";
            ALTER TABLE "Orders" ENABLE TRIGGER "TR_Orders_AuditDates";
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        throw new NotSupportedException(
            "Los códigos originales de CustomerId fueron reemplazados. Para volver al esquema anterior, restaura un respaldo previo a esta migración.");
    }
}
